# Generated by Django 3.2.9 on 2021-11-23 00:00

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicativo_cartas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='texto',
            field=ckeditor.fields.RichTextField(default='10:10:10'),
            preserve_default=False,
        ),
    ]
