# Generated by Django 3.2.9 on 2021-11-23 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicativo_cartas', '0002_post_texto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='hora',
        ),
        migrations.AlterField(
            model_name='post',
            name='data',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
