# Generated by Django 3.2.9 on 2021-11-26 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicativo_cartas', '0003_auto_20211122_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='imagem',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='texto',
            field=models.TextField(),
        ),
    ]
